name: tests

on: [push, pull_request]

jobs:

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
            sudo apt-get update
            sudo apt-get install libgdal-dev gdal-bin libfftw3-dev
      - uses: actions/checkout@v2
        with:
            submodules: true
      - name: Install s2p
        run: pip install -e ".[test]" --upgrade --upgrade-strategy eager
      - name: Run tests
        run: pytest tests
